name: aureus_group
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  lottie: ^1.4.2
  http: ^0.13.4
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          style: normal
    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          style: normal

    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          style: normal
